import type { Metadata } from "next";
import { Ubuntu, Geist_Mono } from "next/font/google";
import QueryClientProviderCom from "@/providers/QueryClientProviderCom";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`dark ${ubuntu.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryClientProviderCom>
          <TooltipProvider>{children}</TooltipProvider>
        </QueryClientProviderCom>
      </body>
    </html>
  );
}
